### ISSUE TITLE
What type of code you want?

### ISSUE THREAD

**Issue by Daksheshapkare** [Ashish-khanagwal/Open-source-practice-and-resources#102]
Hey @Ashish-khanagwal 
I want to contribute more pr in ur repo
I like to  having translation of readme
So which language you suggest
And what other code or changes you want to add it ur repos .
Please let me know i will try my best to make or on it

**Comment by Ashish-khanagwal** [comment]
If you have any resources to add, you can add programming resources. And for now, I don't want it to be translated into any other language.

**Comment by Daksheshapkare** [comment]
> If you have any resources to add, you can add programming resources. And for now, I don't want it to be translated into any other language.

Can I share basic py programs

**Comment by Ashish-khanagwal** [comment]
> > If you have any resources to add, you can add programming resources. And for now, I don't want it to be translated into any other language.
> 
> Can I share basic py programs

Sorry, we just allow resources not any programs/DSA ques
