### ISSUE TITLE
Adding Design Resources

### ISSUE THREAD

**Issue by DevGupta-ikr** [Ashish-khanagwal/Open-source-practice-and-resources#12]
Hey, I could add a few good Design Resources which help Developers in building Websites and applications.

Should I go ahead and create a Pull Request ?

**Comment by Ashish-khanagwal** [comment]
Yea! sure. go ahead and make a pull request

**Comment by DevGupta-ikr** [comment]
Hey, I have created a Pull Request and added the Resources.
