### ISSUE TITLE
Adding Resources for Angular js

### ISSUE THREAD

**Issue by itzwow** [Ashish-khanagwal/Open-source-practice-and-resources#52]
Adding resources for Angular JS as the resources for REACT, Vue is already there adding angular JS resources will make the list complete

**Comment by Ashish-khanagwal** [comment]
okay, go for it

**Comment by AdityaBansal2310** [comment]
I can try to make a whole roadmap for Angular JS.

**Comment by Ashish-khanagwal** [comment]
@AdityaBansal2310 if you want to add a roadmap for angular. go ahead and make sure to add Angular Js in the index, in alphabetical order.

**Comment by AdityaBansal2310** [comment]
I have updated my PR for adding resources for Angular. Kindly look into it and let me know if anything is left out. #59
