### ISSUE TITLE
Adding resources for blockchain development

### ISSUE THREAD

**Issue by archi-jain** [Ashish-khanagwal/Open-source-practice-and-resources#57]
can I add resources and a roadmap for Blockchain Developer

**Comment by Ashish-khanagwal** [comment]
Yea sure!  Go ahead
don't forget to mention it in the index, use this :point_down: 
```
[Blockchain](#blockchain)
```
add this under the index section in alphabetical order

**Comment by Ashish-khanagwal** [comment]
Thank you for your valuable contribution😄
