### ISSUE TITLE
Tranlating

### ISSUE THREAD

**Issue by disabledandfab** [Ashish-khanagwal/Open-source-practice-and-resources#63]
Hi, I'm participating in Hacktoberfest 2022. I'm not great at coding, but I am great at human languages. Wold you like the Read.me translated into Spanish or German?

**Comment by darshil-here** [comment]
Should I translate README.MD to Spanish if @disabledandfab is not available?

**Comment by Ashish-khanagwal** [comment]
> Should I translate README.MD to Spanish if @disabledandfab is not available?

Hey @darshil-here I'll wait for @disabledandfab to make PR, I guess it takes some time to translate it into Spanish.

**Comment by disabledandfab** [comment]
Just submitted the pull request now

**Comment by Ashish-khanagwal** [comment]
@disabledandfab thank you so much for your valuable contribution
