### ISSUE TITLE
Resources for DSA in Java 

### ISSUE THREAD

**Issue by geetika001** [Ashish-khanagwal/Open-source-practice-and-resources#69]
Hey @Ashish-khanagwal Can I please work on this issue and will be adding some awesome resources well researched and notes link.
Please consider it under Hacktoberfest.

**Comment by Ashish-khanagwal** [comment]
@geetika001 sure! go ahead!
Please make sure to mention the module heading in the Index in alphabetical order. :point_down: 
```
[DSA](#dsa)
```

**Comment by AdityaBansal2310** [comment]
Can i also work on it?

**Comment by geetika001** [comment]
@Ashish-khanagwal I have added useful  resources for DSA in #73 .
Please review it and accept the PR under Hacktoberfest.

**Comment by Ashish-khanagwal** [comment]
> Can i also work on it?

this issue already assigned to @geetika001
