### ISSUE TITLE
Translation of readme

### ISSUE THREAD

**Issue by Daksheshapkare** [Ashish-khanagwal/Open-source-practice-and-resources#94]
I want to translate the readme file in French German and many other language
Please assign it to me

**Comment by Ashish-khanagwal** [comment]
Just translate it into those languages in which you feel confident.
Reach out to me on the Discord server if any help is required. Sync and fetch your local repo to avoid any merge conflicts.

**Comment by Daksheshapkare** [comment]
> Can I translated the repo in Hindi,Marathi,Spanish,korean, japanese, gujrati,
> From this you can tell me to which language to translate and other more languages
