### ISSUE TITLE
Fix spanish translation for README.md

### ISSUE THREAD

**Issue by taicoding** [Ashish-khanagwal/Open-source-practice-and-resources#99]
I have read the spanish version of the spanish [README.md](https://github.com/Ashish-khanagwal/Open-source-practice-and-resources) and I find many spelling and grammar mistakes, so as a spanish native speaker I can improve it.

Please assign it to me

**Comment by taicoding** [comment]
The fixes for the spanish translation are in this PR [#100](https://github.com/Ashish-khanagwal/Open-source-practice-and-resources/pull/100#issue-1408671788)

**Comment by Ashish-khanagwal** [comment]
Thank you so much for collaboration
